### ISSUE TITLE
email (widget) probleem

### ISSUE THREAD

**Issue by Podovsky** [redmaner/MA-XML-6.0-DUTCH#60]
Hoi,

Ik heb 2 problemen met de MIUI email app. Het eerste probleem is dat ik op de email widget geen email in kan stellen. Het tweede probleem is dat wanneer ik email krijg en er een melding bovenaan het scherm verschijnt en ik daar dan op klik, er niet wordt doorgeschakeld naar de mail app. MIUI gaat dan terug naar het homescreen zonder email te laten zien. 

Ik heb dit probleem zowel op de Redmi Note 4G als de Redmi 2. Bij MIUI V5 was er nog geen probleem, bij alle versies van MIUI V6 heb ik het probleem. Ik heb ook de officiële ROM geprobeerd en daar was het probleem er niet. Het lijkt een multi lang rom probleem te zijn. 

Zie ook: http://xiaomi.eu/community/threads/redmi-note-4g-email-widget-problems.26602/

Gr.

**Comment by Redmaner** [comment]
Heb je dit probleem ook als de systeemtaal op Engels zet?

**Comment by Podovsky** [comment]
Probleem is er ook als ik Engels selecteer.

**Comment by Podovsky** [comment]
Probleem lijkt verholpen te zijn, zie forum thread.

**Comment by Redmaner** [comment]
Lijkt toch een probleem in de Nederlandse taal

**Comment by Cueie** [comment]
Het tweede probleem heb ik ook.

**Comment by Podovsky** [comment]
Precies. Ik dacht het probleem verholpen te hebben, maar het is nu weer teruggekeerd. Weer terug bij af dus helaas.

**Comment by Cueie** [comment]
Nog steeds geen oplossing?

**Comment by redmaner** [comment]
Nog geen tijd gehad om het probleem op te sporen. Misschien dit weekend

**Comment by Podovsky** [comment]
Ik heb nog even wat testjes gedaan, 2 verschillende roms geprobeerd (tussendoor full wipes)
- Stable official rom 6.3.3. Engels
- Multi lang 5.2.6. Engels / Nederlands

Als eerste heb ik een wipe gedaan en een clean install van de officiele stable rom. Vervolgens Engels geselecteerd (ik kan geen Chinees) en daarna werkt de widget gewoon, ook na rebooten. 

Vervolgens weer een full wipe en clean install van de multilang 5.2.6. gedaan. Als eerste Nederlands geselecteerd, hierna werkt de widget zoals eerder aangegeven niet. Als ik vervolgens de taal verander naar Engels werkt de widget nog steeds niet, maar als ik dan een reboot doe werkt de widget wel. Als je dan de taal weer terugzet naar Nederlands blijft de widget werken. Als je dan weer reboot blijft de widget wel werken, maar volgens mij stopt hij op een gegeven moment. Ik had ditzelfde trucje een tijdje terug geprobeerd maar na een aantal dagen werkte het niet meer. Als je de taal weer terugzet naar Engels werkt het wel weer. 

Het lijkt dus wel een probleem in de multilang/vertaling te zijn mijns inziens.

**Comment by Cueie** [comment]
Ok geen probleem.
Doe maar wanneer je er tij d voor hebt.
Zo het wel willen doen maar weet niet waar te zoeken

**Comment by Podovsky** [comment]
Overigens hebben op mijn Redmi Note 4G alle roms na 5.1.16 meer battery drain, waarschijnlijk door de email app. De synchronisatie blijft soms lang actief (half uur bijvoorbeeld). Bij het accugebruik staat dan de email app ineens bovenaan en verbruikt meer battery dan alle andere applicaties.

**Comment by Podovsky** [comment]
Even een update. Alle problemen die ik had lijken verholpen te zijn in de laatste update 5.3.27. De email widget werkt weer.

**Comment by redmaner** [comment]
Mooi om te horen
