### ISSUE TITLE
Mi4i vertaling bij het bellen

### ISSUE THREAD

**Issue by x2tharay** [redmaner/MA-XML-6.0-DUTCH#98]
Bij het kiezen van een contact in de contactenlijst heb je de keuze om van sim 1 of sim 2 te bellen er staat "choose sim"

**Comment by x2tharay** [comment]
https://drive.google.com/file/d/0B9EPSqcZU2b_S1BPTnlhdnBIVmM/view?usp=docslist_api

**Comment by redmaner** [comment]
@Cueie

**Comment by Cueie** [comment]
reeds vertaald

**Comment by x2tharay** [comment]
Ik zie nog steeds"choose sim card" mi4i V7 miui versie  5.9.1.
