### ISSUE TITLE
Mi4i vertaling bij oproep reageren met sms

### ISSUE THREAD

**Issue by x2tharay** [redmaner/MA-XML-6.0-DUTCH#99]
De standaard teksten staan in het Engels. Kan niet vinden of ik dit in het menu aan te passen is.

**Comment by Cueie** [comment]
Dus wat onder Instellingen> telefoon instellingen> snel antwoord staat.
Heb het bij mij gechecked in die staan wel in het Nederlands.
Anders weet ik niet wat je bedoeld
